'use strict';
/* Guía visual de las canales del Cares. Datos estructurados a partir de las fichas de cares-archive.js (Pyrenaica, 2003). */
const SECTORS={cain:{name:'Caín',photo:'Caín de Valdeón'},valdeon:{name:'Valdeón',photo:'Valdeón Picos de Europa'},ario:{name:'Trea · Ario · Ostón',photo:'Vega de Ario'},bulnes:{name:'Cuesta Duja · Bulnes',photo:'Bulnes Picos de Europa'}};
/* Cotas, horarios, agua y advertencias tal y como figuran en el artículo; sin grados ni datos añadidos. */
const CANAL_META={
'Moéño':{sector:'cain',profile:[['Caín · puente Grande',480],['Majada de Moéño',1310],['Tiro del Joyo La Llera',2008],['Collado',2119],['Collado Jermoso',2084]],time:'Caín–majada 2–2½ h · majada–Collado Jermoso 2–3 h',hours:[4,5.5],water:['Fuente El Palombar'],warn:['El Canalón: el punto más delicado','Caída frecuente de piedras bajo Torre Peñalba','Hielo Pamparroso (nevero en 2003)'],places:['Caín de Valdeón','Collado Jermoso']},
'Arzón':{sector:'cain',profile:[['Majada de Moéño',1310],['Collada Armellán',1395],['Collada de Arzón',1235],['Caín · puente Grande',480]],time:'Majada de Moéño–Arzón–Caín 2–3 h',hours:[2,3],water:['Fuente de Judarriego'],warn:['Caída frecuente de piedras en el fondo de la canal'],places:['Caín de Valdeón']},
'La Sotín':{sector:'valdeon',profile:[['Refugio Diego Mella',2065],['Vega de La Sotín',1450],['Cordinanes',850]],time:'Sin horario propio en el artículo',hours:null,water:[],warn:['Piedra suelta y sendas poco definidas','Precipicios en el Paso de Alfredo','Talladura vertiginosa de La Rienda'],places:['Collado Jermoso','Cordiñanes']},
'Dobresengos':{sector:'cain',profile:[['Caín · puente Grande',480],['Collado Mabro',700],['Collado El Torno',860],['La Gargantada',1900],['Collada Celada',2403],['Torre de la Palanca',2609]],time:'Caín–La Gargantada 3–4 h (sin la prolongación a la Palanca)',hours:[3,4],water:['Fuente Las Piperas','Arroyo habitualmente seco'],warn:['Sedo Mabro: grieta escalonada poco reconocible','Resaltes si te desvías a la izquierda','Prolongación por alta montaña hasta 2609 m'],trepada:true,places:['Caín de Valdeón','Torre de la Palanca']},
'Ría':{sector:'bulnes',profile:[['Puente La Vieya',330],['Jorcain de Cuebre',1025],['Pasadizo La Riega',820],['Collada del Agua',2141]],time:'Itinerario conjunto puente La Vieya → collada del Agua 6–7 h',hours:[6,7],water:[],warn:['Canal de dificultad seria según los autores','Senda expuesta en la bajada por Cuebre'],serious:true,places:['Culiembro','Refugio Jou de los Cabrones']},
'Del Agua':{sector:'bulnes',profile:[['Pasadizo La Riega',820],['Collada del Agua',2141],['Refugio J. R. Lueje',2070]],time:'Itinerario completo desde puente La Vieya 6–7 h',hours:[6,7],water:['Agua en el cauce (no garantizada)'],warn:['Entrada directa impracticable','Trepada por pared muy inclinada junto a cascadas','Evitar el canalizo izquierdo antes de 2000 m'],trepada:true,places:['Refugio Jou de los Cabrones']},
'Piedra Bellida':{sector:'bulnes',profile:[['Antiguo puente de Trea',440],['Jorcain de Cuebre',1025],['Pasadizo La Riega',820],['Horcado Turonero',940],['Collado Cerredo',1450],['Collado Cima',1385],['Bulnes · Castillo',715],['Puente La Jaya',250]],time:'Senda–Cerredo 5–6 h · Cerredo–Bulnes–La Jaya 2½–3 h',hours:[7.5,9],water:['Fuente Prieta','Cuañegra','Fuente del Tornu'],warn:['Pardo de Cuesta Duja: paso aéreo','Rampa con gravilla resbaladiza al bajar'],places:['Bulnes','Poncebos']},
'Trea':{sector:'ario',profile:[['Puente Bolín',440],['Cuarroble',1025],['Las Cruces de Ario',1580],['Refugio Vega de Ario',1625]],time:'Puente Bolín–refugio de Ario 4–5 h',hours:[4,5],water:['Fuente Cuarroble'],warn:['Paso más delicado tras el collain Huerto de Rey','Al bajar: salir de la canal ~250 m bajo la fuente Cuarroble'],places:['Refugio Vega de Ario','Caín de Valdeón']},
'Culiembro':{sector:'ario',profile:[['Refugio Vega de Ario',1625],['Collado',1662],['Prados de Ostón',1010],['Majada de Culiembro',450]],time:'Ario–Ostón 1½–2 h · Ostón–Culiembro 1½–2 h',hours:[3,4],water:['Fuente Gonzomera'],warn:['Senda tallada en zigzag bajo La Peña'],places:['Refugio Vega de Ario','Culiembro']},
'La Raya o La Viña':{sector:'ario',profile:[['Ostón',1010],['La Viña · Senda del Cares',425]],time:'Ostón–La Raya–La Viña 1½–2 h',hours:[1.5,2],water:['Abrevadero de Valdelafuente'],warn:['La canal directa era impracticable (2003)','Exposición; transitabilidad actual no acreditada'],places:['Culiembro']},
'La Jerrera':{sector:'cain',profile:[['Caín de Abajo',480],['Sedo de Oliseda',1175],['Majada de Oliseda',1450],['Collado Joracao',1829],['Jultayo',1940]],time:'Subida 5–6 h · regreso por Hierbas Altas 3–4 h',hours:[8,10],water:['Fuente de Oliseda','Fuente Cuarroble','Agua La Bersolina'],warn:['Sedo de Oliseda: trepada casi vertical de ~12 m (experiencia en escalada)','Variante por Monero: más larga y, según los autores, más segura'],trepada:true,places:['Caín de Valdeón','Jultayu']},
'Mesones':{sector:'cain',profile:[['Caín de Abajo',480],['Caín de Arriba',620],['Sedo Armao',1080],['Majada de Mesones',1450]],time:'Caín–majada Mesones–Carbanal 4–4½ h',hours:[4,4.5],water:['Fuente El Cuciao','Fuente de Mesones (seca en verano)','Fuente El Frade'],warn:['Sedo Mesones: delicado (barrenado en los 80)','Sedo Armao: escalones y paso estrecho'],places:['Caín de Valdeón']},
'Capozo':{sector:'valdeon',profile:[['Mirador del Tombo',830]],time:'Carbanal–Capozo–El Tombo 2½–3 h',hours:[2.5,3],water:['Joyo del Cabrero','Cueva del Agua','La Farfada'],warn:['Pared corta en la parte alta','Zigzags tallados del Cabido Cimero'],places:['Mirador del Tombo','Cordiñanes']},
'Pambuches':{sector:'valdeon',profile:[['Posada de Valdeón',940],['Collado de Pantivalles',1180],['Collado Pambuches',1880],['Collado',2334],['La Bermeja',2393]],time:'Posada–collado Pambuches–La Bermeja 3–4 h',hours:[3,4],water:['Fuente de Hoyobladas','Pilón de Piergua','Fuente del Hurden'],warn:['Casi 1500 m de desnivel desde Posada'],places:['Posada de Valdeón','Peña Bermeja']},
'Del Perro':{sector:'valdeon',profile:[['La Bermeja',2393],['Cimera del Frade',1800],['Vega Llos',1540],['Soto de Valdeón',945]],time:'La Bermeja–canal del Perro–Vega Llos–Soto 2½–3 h',hours:[2.5,3],water:['Vega Llos: fuente-abrevadero','Manantial de Juan Burón'],warn:['Cresta con cuatro brechas y pasos aéreos (experiencia en escalada)','Alternativa por terreno muy descompuesto','Posible nevero a principios de verano'],trepada:true,places:['Soto de Valdeón','Peña Bermeja']}
};
/* Documentación complementaria con fuente y fecha (revisada en septiembre de 2026 en la versión 5 de la app). */
const CANAL_EXTRA={'Trea':{reviewed:'2026-09-10',sources:[{id:'R1',name:'Refugio Vega de Ario · cómo llegar',url:'https://www.refugiovegadeario.es/como-llegar/'},{id:'R2',name:'Reseña Wikiloc · Caín–Canal de Trea–Vega de Ario (agosto 2026)',url:'https://es.wikiloc.com/rutas-senderismo/28-8-2026-anillo-vindio-etapa-cain-canal-de-trea-refugio-vega-de-ario-283433297'},{id:'R3',name:'Parque Nacional · avisos de acceso (junio 2026)',url:'https://parquenacionalpicoseuropa.es/2026/06/'}],notes:[['Distancia y desnivel según el refugio','Unos 4 km, 1.200 m de desnivel y 3,5 h para el acceso desde el Cares; concentra esos 1.200 m en unos 3 km de canal. Lo describe como moderado, sin pasos técnicos ni aéreos.','R1'],['Recorrido completo desde Caín','Una reseña de agosto de 2026 registra 8,85 km y 1.536 m de ascenso desde Caín y lo clasifica como difícil. Recorridos y criterios distintos al del refugio.','R2'],['Agua citada recientemente','El refugio menciona un manantial a mitad de canal; la reseña cita Fuente El Peyu, Collado Las Cruces y Fuente Las Jallellas. No confirma caudal ni potabilidad el día de tu salida.','R1 · R2'],['Incendio de 2025','El Parque recogió la reapertura del Cares y de canales practicables, incluida Trea, desde el 6 de noviembre de 2025 tras el incendio de ese verano. Comprueba los avisos vigentes antes de salir.','R3']]}};
const CN={filter:'all',query:'',selected:null,photos:{},geo:{},map:null,layer:null};
try{CN.geo=JSON.parse(localStorage.getItem('tm.geo.v1'))||{}}catch{}
const canales=(typeof CARES_ROUTES!=='undefined'?CARES_ROUTES:[]).map((r,i)=>({...r,i,...(CANAL_META[r.name]||{profile:[],warn:[],water:[],places:[]})}));
function ascent(p){let up=0;for(let i=1;i<p.length;i++)if(finite(p[i][1])&&finite(p[i-1][1])&&p[i][1]>p[i-1][1])up+=p[i][1]-p[i-1][1];return up}
const eles=c=>c.profile.map(p=>p[1]).filter(finite);
function badges(c){const e=eles(c),out=[];if(c.hours)out.push(`<span class="cn-badge time">⏱ ${c.hours[0]===c.hours[1]?c.hours[0]:String(c.hours[0]).replace('.',',')+'–'+String(c.hours[1]).replace('.',',')} h</span>`);if(e.length>1)out.push(`<span class="cn-badge up">▲ ${fmt(Math.max(...e))} m</span>`);if(c.serious)out.push('<span class="cn-badge serious">Dificultad seria</span>');if(c.trepada)out.push('<span class="cn-badge warn">Trepada / paso aéreo</span>');if(c.water.length)out.push(`<span class="cn-badge water">💧 ${c.water.length}</span>`);return out.join('')}
function sparkline(c,w=300,h=70){const p=c.profile.filter(x=>finite(x[1]));if(p.length<2)return '<p class="cn-route">Cotas insuficientes en el artículo para dibujar el perfil.</p>';const lo=Math.min(...p.map(x=>x[1])),hi=Math.max(...p.map(x=>x[1])),X=i=>8+i/(p.length-1)*(w-16),Y=v=>h-10-(v-lo)/Math.max(1,hi-lo)*(h-24);const d=p.map((x,i)=>`${i?'L':'M'}${X(i).toFixed(1)},${Y(x[1]).toFixed(1)}`).join(' ');return `<svg class="cn-spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-label="Perfil de cotas: ${p.map(x=>x[1]+' m').join(', ')}"><defs><linearGradient id="cnGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#c4ff3d" stop-opacity=".35"/><stop offset="1" stop-color="#38e1ff" stop-opacity="0"/></linearGradient></defs><path class="area" d="${d} L${X(p.length-1)},${h} L${X(0)},${h} Z"/><path class="line" d="${d}"/>${p.map((x,i)=>`<circle cx="${X(i)}" cy="${Y(x[1])}" r="2.6"/>`).join('')}<text x="6" y="11">${fmt(p[0][1])} m</text><text x="${w-6}" y="11" text-anchor="end">${fmt(p.at(-1)[1])} m</text></svg>`}
function profileSVG(c){const p=c.profile.filter(x=>finite(x[1]));if(p.length<2)return '<p class="muted">El artículo no publica cotas suficientes para esta canal.</p>';const w=760,h=300,lo=Math.min(...p.map(x=>x[1]))-80,hi=Math.max(...p.map(x=>x[1]))+80,X=i=>70+i/(p.length-1)*(w-140),Y=v=>h-62-(v-lo)/(hi-lo)*(h-110);const d=p.map((x,i)=>`${i?'L':'M'}${X(i).toFixed(1)},${Y(x[1]).toFixed(1)}`).join(' ');return `<svg class="cn-profile" viewBox="0 0 ${w} ${h}" role="img" aria-label="Perfil de cotas del itinerario descrito"><defs><linearGradient id="cnGrad2" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#c4ff3d" stop-opacity=".4"/><stop offset="1" stop-color="#38e1ff" stop-opacity="0"/></linearGradient></defs><path class="area" d="${d} L${X(p.length-1)},${h-62} L${X(0)},${h-62} Z"/><path class="line" d="${d}"/>${p.map((x,i)=>`<circle cx="${X(i)}" cy="${Y(x[1])}" r="6"/><text x="${X(i)}" y="${Y(x[1])-14}" text-anchor="middle">${fmt(x[1])} m</text><text class="lbl" x="${X(i)}" y="${h-30+(i%2)*20}" text-anchor="middle">${esc(x[0].length>22?x[0].slice(0,21)+'…':x[0])}</text>`).join('')}</svg><p class="footnote">Puntos y cotas citados en el artículo, unidos en orden. No es un perfil topográfico: entre puntos el terreno puede subir y bajar.</p>`}
function filtered(){const q=CN.query.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'');return canales.filter(c=>{if(CN.filter==='water'&&!c.water.length)return false;if(CN.filter==='trepada'&&!(c.trepada||c.serious))return false;if(CN.filter==='long'&&!(c.hours&&c.hours[1]>=6))return false;if(SECTORS[CN.filter]&&c.sector!==CN.filter)return false;if(q){const hay=(c.name+' '+c.connection+' '+c.profile.map(p=>p[0]).join(' ')+' '+c.sections.map(s=>s[1]).join(' ')).toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'');return q.split(/\s+/).every(w=>hay.includes(w))}return true})}
function renderGrid(){const list=filtered();$('#cnGrid').innerHTML=list.length?list.map((c,k)=>`<button type="button" class="cn-card" data-canal="${c.i}" style="animation-delay:${k*40}ms"><div class="cn-photo" data-photo-sector="${c.sector}" data-photo-index="${c.i}"><span class="cn-num">CANAL ${String(c.i+1).padStart(2,'0')}</span><span class="cn-sector">${esc(SECTORS[c.sector]?.name||'')}</span></div><div class="cn-content"><h3>${esc(c.name)}</h3><p class="cn-route">${esc(c.connection)}</p>${sparkline(c)}<div class="cn-badges">${badges(c)}</div></div></button>`).join(''):'<p class="muted">Ninguna canal coincide con el filtro.</p>';paintCardPhotos()}
async function sectorPhotos(sector){if(CN.photos[sector])return CN.photos[sector];CN.photos[sector]=globalThis.TMPhotos?await TMPhotos.commonsPhotos(SECTORS[sector].photo,8):[];return CN.photos[sector]}
async function paintCardPhotos(){for(const el of $$('#cnGrid .cn-photo')){const list=await sectorPhotos(el.dataset.photoSector);const p=list[(+el.dataset.photoIndex)%Math.max(1,list.length)];if(p&&el.isConnected){el.style.backgroundImage=`url("${p.url.replace(/"/g,'%22')}")`;el.title=p.title+' · '+p.artist+' · '+p.license}}}
function contextFor(c){const extra=CANAL_EXTRA[c.name];return{canal:c.name,conexion:c.connection,cotas_citadas:c.profile.map(([n,e])=>`${n}${finite(e)?' '+e+' m':''}`),horario_articulo:c.time,agua_citada_2003:c.water,advertencias_articulo:c.warn,dificultad_seria_segun_autores:!!c.serious,secciones:c.sections.map(([t,x])=>({[t]:x})),fuente:`${CARES_SOURCE.authors} (2003), «${CARES_SOURCE.title}», ${CARES_SOURCE.publication}. ${CARES_SOURCE.pdf}`,documentacion_complementaria:extra?{revisada:extra.reviewed,notas:extra.notes.map(([t,x,s])=>`${t}: ${x} [${s}]`),fuentes:extra.sources}:null,limite:'Descripción de 2003: no acredita estado actual, señalización, agua ni apertura. No es guía GPS.'}}
function searchLink(q){return 'https://www.google.com/search?q='+encodeURIComponent(q)}
function linksFor(c,geo){const name='Canal de '+c.name;const L=[[`Artículo original · Pyrenaica 211`,`Morán y Lozano (2003), páginas del PDF ${c.pages.join(', ')}`,`${CARES_SOURCE.pdf}#page=${c.pages[0]}`],['Parque Nacional de los Picos de Europa','Avisos, cierres y normativa oficiales','https://parquenacionalpicoseuropa.es/'],['AEMET · predicción de montaña','Boletín oficial Picos de Europa','https://www.aemet.es/es/eltiempo/prediccion/montana'],['Wikiloc · tracks de la canal','Búsqueda de rutas públicas recientes',searchLink(name+' Picos de Europa site:wikiloc.com')],['Reseñas recientes','Blogs y crónicas (filtra por fecha)',searchLink('"'+name+'" Picos de Europa')]];
 if(geo){L.push(['Mapa topográfico','OpenTopoMap en la zona',`https://opentopomap.org/#map=15/${geo.lat.toFixed(5)}/${geo.lon.toFixed(5)}`]);L.push(['OpenStreetMap','Caminos cartografiados',`https://www.openstreetmap.org/?mlat=${geo.lat.toFixed(5)}&mlon=${geo.lon.toFixed(5)}#map=15/${geo.lat.toFixed(5)}/${geo.lon.toFixed(5)}`])}
 for(const s of CANAL_EXTRA[c.name]?.sources||[])L.push([s.name,'Fuente ['+s.id+'] de la documentación complementaria',s.url]);L.push(['Emergencias 112','Asturias · Castilla y León','tel:112']);return L.map(([t,s,u])=>`<a href="${esc(u)}" ${u.startsWith('tel:')?'':'target="_blank" rel="noopener"'}><b>${esc(t)} ${u.startsWith('tel:')?'☎':'↗'}</b><small>${esc(s)}</small></a>`).join('')}
async function geocode(place){if(CN.geo[place]!==undefined)return CN.geo[place];const u='https://nominatim.openstreetmap.org/search?'+new URLSearchParams({q:place,format:'json',limit:'1',viewbox:'-5.25,43.40,-4.55,43.02',bounded:'1','accept-language':'es'});try{const r=await fetch(u,{headers:{Accept:'application/json'}});if(!r.ok)throw Error();const d=await r.json();const hit=d?.[0]?{lat:+d[0].lat,lon:+d[0].lon,label:d[0].display_name}:null;CN.geo[place]=hit&&finite(hit.lat)&&finite(hit.lon)?hit:null}catch{return null}try{localStorage.setItem('tm.geo.v1',JSON.stringify(CN.geo))}catch{}return CN.geo[place]}
async function geocodeAll(c){const out=[];for(const p of c.places||[]){const cached=CN.geo[p]!==undefined;const g=await geocode(p);if(g)out.push({...g,place:p});if(!cached)await new Promise(r=>setTimeout(r,1100))}return out}
async function drawMap(c,el){const pts=await geocodeAll(c);if(CN.selected!==c||!el.isConnected)return pts;if(!pts.length||!window.L){el.outerHTML='<p class="footnote">No se pudieron situar los lugares en el mapa (OpenStreetMap/Nominatim). Usa los enlaces de abajo.</p>';return pts}CN.map?.remove();CN.map=L.map(el,{scrollWheelZoom:false,maxZoom:17});L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(CN.map);const g=L.featureGroup(pts.map(p=>L.circleMarker([p.lat,p.lon],{radius:9,color:'#c4ff3d',weight:3,fillColor:'#06101b',fillOpacity:1}).bindPopup(`<b>${esc(p.place)}</b><br><small>Ubicación aproximada según OpenStreetMap (Nominatim). No es el trazado de la canal.</small>`))).addTo(CN.map);if(pts.length>1)CN.map.fitBounds(g.getBounds(),{padding:[40,40],maxZoom:14});else CN.map.setView([pts[0].lat,pts[0].lon],13);setTimeout(()=>CN.map?.invalidateSize(),250);return pts}
function openCanal(i){const c=canales.find(x=>x.i===i);if(!c)return;CN.selected=c;const e=eles(c),extra=CANAL_EXTRA[c.name];if(typeof sfx==='function')sfx('open');
 document.body.insertAdjacentHTML('beforeend',`<div class="cn-detail" id="cnDetail" role="dialog" aria-modal="true" aria-labelledby="cnTitle"><div class="cn-sheet"><div class="cn-sheet-hero" id="cnHero"><button class="quiet cn-close" type="button" id="cnClose" aria-label="Cerrar ficha">✕</button><div><p class="eyebrow">CANAL ${String(c.i+1).padStart(2,'0')} · ${esc(SECTORS[c.sector]?.name||'')}</p><h2 id="cnTitle">${esc(c.name)}</h2><p>${esc(c.connection)}</p><p class="cn-credit" id="cnCredit"></p></div></div><div class="cn-sheet-body">
 <div class="cn-kpis"><div><strong>${e.length?fmt(Math.min(...e)):'—'}</strong><span>Cota mínima citada (m)</span></div><div><strong>${e.length?fmt(Math.max(...e)):'—'}</strong><span>Cota máxima citada (m)</span></div><div><strong>${e.length>1?'+'+fmt(ascent(c.profile)):'—'}</strong><span>Subida entre cotas citadas (m)</span></div><div><strong>${c.hours?String(c.hours[0]).replace('.',',')+'–'+String(c.hours[1]).replace('.',',')+' h':'—'}</strong><span>${esc(c.time)}</span></div></div>
 <div class="cn-badges">${badges(c)}</div>
 <div class="cn-actions"><button class="primary" type="button" id="cnWikiloc">⚡ Buscar track y planificar</button><button class="quiet" type="button" id="cnWeather">🌦 Tiempo en la zona</button><button class="quiet" type="button" id="cnAsk">✦ Preguntar al copiloto</button><button class="quiet" type="button" id="cnResearch">🔎 Investigar estado actual</button></div>
 <h3>Perfil de cotas</h3>${profileSVG(c)}
 ${c.warn.length?`<h3>Pasos delicados según el artículo</h3><div class="cn-badges">${c.warn.map(w=>`<span class="cn-badge warn">⚠ ${esc(w)}</span>`).join('')}</div>`:''}
 ${c.water.length?`<h3 style="margin-top:18px">Agua citada (2003)</h3><div class="cn-badges">${c.water.map(w=>`<span class="cn-badge water">💧 ${esc(w)}</span>`).join('')}</div><p class="footnote">Referencias históricas: no confirman caudal ni potabilidad actuales.</p>`:''}
 <h3 style="margin-top:22px">El itinerario, paso a paso</h3><ol class="cn-steps">${c.sections.map(([t,x],k)=>`<li data-n="${k+1}"><h4>${esc(t)}</h4><p>${esc(x)}</p></li>`).join('')}</ol>
 ${extra?`<h3>Documentación complementaria</h3><p class="footnote">Revisada ${esc(extra.reviewed)}. Fuentes con fecha; no sustituyen a los avisos vigentes.</p><ol class="cn-steps">${extra.notes.map(([t,x,s],k)=>`<li data-n="${String.fromCharCode(65+k)}"><h4>${esc(t)}</h4><p>${esc(x)} <small class="muted">[${esc(s)}]</small></p></li>`).join('')}</ol>`:''}
 <h3>Mapa de referencias</h3><div class="cn-map" id="cnMap"><p class="footnote" style="padding:16px"><span class="spinner"></span>Situando lugares…</p></div>
 <div class="cn-ai" id="cnAI" hidden></div>
 <h3 style="margin-top:22px">Fuentes para contrastar</h3><div class="cn-links" id="cnLinks">${linksFor(c,null)}</div>
 <p class="footnote">Ficha basada en ${esc(CARES_SOURCE.authors)} (2003), «${esc(CARES_SOURCE.title)}», ${esc(CARES_SOURCE.publication)}. Describe lo publicado entonces: no acredita condiciones actuales ni es una guía GPS. Consulta siempre los avisos del Parque y de AEMET.</p></div></div></div>`);
 const close=()=>{CN.map?.remove();CN.map=null;$('#cnDetail')?.remove();document.removeEventListener('keydown',onKey);if(typeof sfx==='function')sfx('close')};const onKey=ev=>{if(ev.key==='Escape')close()};document.addEventListener('keydown',onKey);
 $('#cnClose').onclick=close;$('#cnDetail').onclick=ev=>{if(ev.target.id==='cnDetail')close()};$('#cnClose').focus({preventScroll:true});
 $('#cnWikiloc').onclick=()=>{close();showTab('route');const q='Canal de '+c.name+' Picos de Europa';if($('#wlQuery')){$('#wlQuery').value=q;$$('#routeFinder [data-finder]')[0]?.click();TMWikiloc.search(q);$('#routeFinder').scrollIntoView({behavior:'smooth'})}};
 $('#cnWeather').onclick=async()=>{const g=(await geocodeAll(c))[0];close();if(g)setLocation({name:'Canal de '+c.name+' · '+g.place,lat:g.lat,lon:g.lon});showTab('now')};
 $('#cnAsk').onclick=()=>{globalThis.Copilot?.ask(`Explícame la canal de ${c.name}: qué la hace especial, sus pasos delicados, el agua, cuánto se tarda y para quién es adecuada. Relaciónalo con el tiempo previsto que tengas en los datos.`,{label:'✦ Canal de '+c.name})};
 $('#cnResearch').onclick=async()=>{const out=$('#cnAI');out.hidden=false;out.innerHTML='<p><span class="spinner"></span>Buscando información actual sobre la canal…</p>';const res=await globalThis.Copilot?.ask(`Investiga en internet el estado actual y la información más reciente de la Canal de ${c.name} (Picos de Europa): accesos y cierres del Parque, desprendimientos, señalización, agua, reseñas recientes con fecha. Compara con la ficha de 2003 y cita cada fuente.`,{research:'Canal de '+c.name+' Picos de Europa',label:'🔎 Estado actual: Canal de '+c.name});out.innerHTML=res?`<p class="eyebrow">INVESTIGACIÓN IA</p><div class="cn-ai-out">${Copilot.md(res.text)}</div>${res.sources?.length?'<div class="cp-sources">'+res.sources.slice(0,8).map(s=>{const h=safeLink(s.url);return h?`<a href="${esc(h)}" target="_blank" rel="noopener">↗ ${esc(String(s.title).slice(0,48))}</a>`:''}).join('')+'</div>':''}<p class="footnote">Generado por IA a partir de fuentes web. Puede equivocarse: abre las fuentes.</p>`:'<p>La investigación no se completó. Revisa el copiloto.</p>'};
 drawMap(c,$('#cnMap')).then(pts=>{if(pts[0]&&$('#cnLinks'))$('#cnLinks').innerHTML=linksFor(c,pts[0])});
 (async()=>{let list=globalThis.TMPhotos?await TMPhotos.commonsPhotos('Canal de '+c.name+' Picos de Europa',4):[];if(!list.length)list=await sectorPhotos(c.sector);const p=list[c.i%Math.max(1,list.length)];if(p&&$('#cnHero')){try{await TMPhotos.preload(p.url)}catch{return}if(!$('#cnHero'))return;$('#cnHero').style.backgroundImage=`url("${p.url.replace(/"/g,'%22')}")`;$('#cnCredit').innerHTML=TMPhotos.creditHTML(p)}})()}
function mountCanales(){const host=$('#canalesApp');if(!host||!canales.length)return;const all=canales.flatMap(eles),hours=canales.filter(c=>c.hours);
 host.insertAdjacentHTML('afterbegin',`<section id="canalesVisual"><div class="cn-hero"><div class="cn-hero-photo" id="cnHeroPhoto"></div><div><p class="eyebrow">GUÍA VISUAL · PICOS DE EUROPA</p><h2>Las canales<br><em>del Cares</em></h2><p>Quince pasos históricos entre el río y las majadas: perfiles, pasos delicados, agua, horarios y fuentes para contrastar. Busca su track en Wikiloc y planifícala con el tiempo real.</p></div></div>
 <div class="cn-kpis"><div><strong>${canales.length}</strong><span>canales documentadas</span></div><div><strong>${fmt(Math.min(...all))}</strong><span>m · cota más baja citada</span></div><div><strong>${fmt(Math.max(...all))}</strong><span>m · cota más alta citada</span></div><div><strong>${hours.filter(c=>c.hours[1]>=6).length}</strong><span>itinerarios de 6 h o más</span></div></div>
 <input id="cnSearch" class="cn-search" type="search" placeholder="Buscar canal, majada, fuente, collado…" aria-label="Buscar en las canales">
 <div class="cn-filters" role="toolbar" aria-label="Filtros">${[['all','Todas'],...Object.entries(SECTORS).map(([k,v])=>[k,v.name]),['water','💧 Con agua citada'],['trepada','⚠ Trepada o seria'],['long','⏱ 6 h o más']].map(([k,l])=>`<button type="button" data-cn-filter="${k}" aria-pressed="${k==='all'}">${esc(l)}</button>`).join('')}</div>
 <div class="cn-grid" id="cnGrid"></div><p class="footnote">Datos del artículo de ${esc(CARES_SOURCE.authors)} (Pyrenaica, 2003). Las descripciones de 2003 no acreditan el estado actual. Antes de salir consulta los avisos del Parque Nacional y de AEMET.</p></section>`);
 renderGrid();$('#cnGrid').onclick=e=>{const b=e.target.closest('[data-canal]');if(b)openCanal(+b.dataset.canal)};
 $('.cn-filters').onclick=e=>{const b=e.target.closest('[data-cn-filter]');if(!b)return;CN.filter=b.dataset.cnFilter;$$('[data-cn-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderGrid()};
 $('#cnSearch').oninput=e=>{CN.query=e.target.value.trim();renderGrid()};
 globalThis.TMPhotos?.commonsPhotos('Garganta del Cares',6).then(async l=>{const p=l[new Date().getDate()%Math.max(1,l.length)];if(!p)return;try{await TMPhotos.preload(p.url)}catch{return}const el=$('#cnHeroPhoto');if(el){el.style.backgroundImage=`url("${p.url.replace(/"/g,'%22')}")`;el.classList.add('on');el.title=p.title+' · '+p.artist+' · '+p.license}})}
mountCanales();
globalThis.TMCanales={get selected(){return CN.selected},contextFor,open:openCanal,list:canales};
