'use strict';
/* Modo «En ruta»: cabina GPS, retorno y luz, brújula, tormenta, track propio, vigilancia meteorológica y SOS. */
const FC=FieldCore;
const FS={watch:null,pos:null,track:[],startedAt:null,wake:null,heading:null,headingSrc:null,map:null,me:null,acc:null,crumb:null,routeLayer:null,off:{count:0,alerted:false},turnAlarm:{warned:false,fired:false},lastWeather:0,lastProgress:0,flashAt:null,flashTimer:null,strikes:[],whistle:null,strobe:null,lastSave:0};
const fTime=t=>Number.isFinite(t)?new Date(t).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}):'—';
const fDur=ms=>{if(!Number.isFinite(ms))return'—';const neg=ms<0,m=Math.round(Math.abs(ms)/60000),h=Math.floor(m/60);return(neg?'−':'')+(h?`${h} h ${String(m%60).padStart(2,'0')}`:`${m} min`)};
function lsGet(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}
function lsSet(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const ICON={sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>'};

$('#fieldApp').innerHTML=`<div class="field-hero"><div><p class="eyebrow">MODO MONTAÑA · PARA JORNADAS LARGAS</p><h2>En ruta</h2></div><div class="field-state" id="fieldState"><i></i><span>GPS apagado</span></div></div>
<div class="field-actions"><button class="primary" type="button" id="fieldStart">▶ Iniciar seguimiento</button><button class="quiet" type="button" id="fieldStop" hidden>■ Detener</button><label class="check"><input type="checkbox" id="fieldWake" checked> Pantalla encendida</label><label class="check"><input type="checkbox" id="fieldRecord" checked> Grabar mi track</label><label class="check">Aviso fuera de ruta a <input type="number" id="offThreshold" min="30" max="1000" step="10" value="120" style="width:96px;min-height:40px;padding:6px 12px"> m</label></div>
<div id="fieldAlerts" class="field-alerts" aria-live="assertive"></div>
<div class="readouts" id="fieldReadouts"></div>
<div class="field-map" id="fieldMap" aria-label="Mapa de seguimiento"></div>
<p class="footnote">Funciona con la web abierta en primer plano: con el teléfono bloqueado, iOS pausa el GPS de las páginas web. Para ahorrar batería usa el tema Noche (menú Más) y baja el brillo. La posición no se envía a ningún servidor.</p>
<div class="field-grid">
<section class="card"><p class="eyebrow">RETORNO Y LUZ · SIN CONEXIÓN</p><h3>Hora límite</h3><div class="turn" id="turnTime">—</div><p id="turnText" class="muted">Inicia el seguimiento o carga una ruta.</p><div class="route-settings"><label>Tipo de recorrido<select id="turnMode"><option value="outback">Ida y vuelta (mismo camino)</option><option value="through">Travesía o circular</option></select></label><label>Margen antes del ocaso (min)<input id="turnMargin" type="number" min="0" max="240" step="5" value="45"></label></div><div class="sunline" id="sunLine"></div><div class="sun-rows" id="sunRows"></div><p class="footnote">Sol y luna calculados en el dispositivo para tu posición (fórmulas astronómicas, sin internet). No contemplan la sombra del relieve: en canales y valles cerrados oscurece antes.</p></section>
<section class="card"><p class="eyebrow">ORIENTACIÓN</p><h3>Brújula y regreso</h3><div class="compass-wrap"><div class="compass" id="compass"></div><div class="compass-read"><strong id="compassHeading">—</strong><span class="muted" id="compassSrc">Activa la brújula del teléfono</span><select id="compassTarget" aria-label="Destino"></select><div id="compassTargetInfo" class="muted"></div></div></div><div class="action-row"><button class="quiet" type="button" id="compassEnable">🧭 Activar brújula</button><input id="pointName" maxlength="40" placeholder="Nombre (coche, cruce…)" style="flex:1;min-width:140px"><button class="quiet" type="button" id="pointSave">📍 Guardar punto</button></div><p class="footnote">Calibra moviendo el teléfono en forma de 8. Las brújulas de móvil se desvían cerca de metales y fundas imantadas: contrasta con el terreno y el mapa.</p></section>
<section class="card"><p class="eyebrow">TORMENTA · REGLA 30/30</p><h3>¿A qué distancia cae el rayo?</h3><div class="storm-buttons"><button type="button" class="flash" id="flashBtn">⚡ Relámpago</button><button type="button" class="quiet" id="thunderBtn" disabled>🔊 Trueno</button></div><div class="storm-out" id="stormOut"><p class="muted">Pulsa al ver el relámpago y otra vez al oír el trueno.</p></div></section>
<section class="card"><p class="eyebrow">MI TRACK</p><h3>Lo que llevas hecho</h3><div class="sun-rows" id="trackStats"></div><div class="action-row"><button class="quiet" type="button" id="trackGpx">⬇ Descargar GPX</button><button class="quiet" type="button" id="trackUse">Usar como ruta</button><button class="quiet" type="button" id="trackClear">Borrar</button></div><p class="footnote" id="trackNote">Se guarda en este dispositivo mientras grabas; si cierras la web por error, se recupera al volver.</p></section>
<section class="card"><p class="eyebrow">VIGILANCIA METEOROLÓGICA</p><h3>Próximas 3 horas donde estás</h3><div id="watchOut" class="muted">Con el seguimiento activo y cobertura, se consulta cada 20 minutos y te avisa si aparece tormenta, rachas fuertes o lluvia intensa.</div><div class="action-row"><button class="quiet" type="button" id="watchNow">↻ Comprobar ahora</button></div></section>
<section class="card"><p class="eyebrow">AGUA Y REFUGIOS</p><h3>A lo largo de tu ruta</h3><div id="fieldPois" class="muted">Carga una ruta en el planificador para ver fuentes y refugios cercanos al track.</div></section>
</div>
<section class="card sos-panel" id="sosPanel"><p class="eyebrow">EMERGENCIA</p><h2>SOS</h2><div id="sosCoords"><p class="muted">Sin posición todavía.</p></div><div class="sos-actions"><a class="call" href="tel:112">☎ Llamar al 112</a><button type="button" id="sosLocate">📍 Obtener mi posición</button><a id="sosSms" href="sms:">✉ SMS a mi contacto</a><button type="button" id="sosShare">↗ Compartir posición</button><button type="button" id="sosCopy">⧉ Copiar mensaje</button><button type="button" id="sosWhistle">📣 Silbato SOS</button><button type="button" id="sosStrobe">🔦 Luz SOS</button></div><details><summary>Ficha para el rescate · guardada solo aquí</summary><form class="medical" id="medical"><label>Nombre<input name="name" maxlength="80" autocomplete="name"></label><label>Teléfono de contacto<input name="phone" maxlength="30" type="tel" autocomplete="tel"></label><label>Grupo sanguíneo<input name="blood" maxlength="8"></label><label>Alergias<input name="allergies" maxlength="160"></label><label class="wide">Medicación y enfermedades<input name="meds" maxlength="240"></label><label class="wide">Notas (ruta prevista, compañeros, color de ropa…)<textarea name="notes" maxlength="500" rows="2"></textarea></label></form></details><p class="footnote">En España y la UE el 112 es gratuito y funciona con cualquier operador con cobertura. En el mensaje van las coordenadas en grados y en UTM, que es el formato que suelen pedir los equipos de rescate. Si hay poca batería, envía primero un SMS: necesita menos señal que una llamada.</p></section>`;

/* ---------- Ficha médica ---------- */
const medical=$('#medical');const med=lsGet('tm.medical',{});for(const [k,v] of Object.entries(med))if(medical.elements[k])medical.elements[k].value=v;
medical.addEventListener('input',()=>{const d={};for(const el of medical.elements)if(el.name)d[el.name]=el.value;lsSet('tm.medical',d);renderSOS()});

/* ---------- Mapa ---------- */
function ensureFieldMap(){if(FS.map||!window.L||$('#fieldMap').offsetParent===null)return;FS.map=L.map('fieldMap',{zoomControl:true,maxZoom:18});L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(FS.map);const c=FS.pos||S.location;FS.map.setView([c.lat,c.lon],13);drawFieldRoute();drawCrumb()}
function drawFieldRoute(){if(!FS.map)return;FS.routeLayer?.remove();FS.routeLayer=null;const r=S.route;if(!r)return;const groups=new Map();for(const p of r.points){if(!groups.has(p.segment))groups.set(p.segment,[]);groups.get(p.segment).push([p.lat,p.lon])}FS.routeLayer=L.featureGroup([...groups.values()].map(g=>L.polyline(g,{color:'#0a5cff',weight:5,opacity:.85}))).addTo(FS.map);if(!FS.pos)FS.map.fitBounds(FS.routeLayer.getBounds(),{padding:[24,24]});globalThis.TMPois?.drawOn(FS.map)}
function drawCrumb(){if(!FS.map)return;if(!FS.crumb)FS.crumb=L.polyline([],{color:'#ff4d1f',weight:4,dashArray:'2 8',lineCap:'round'}).addTo(FS.map);FS.crumb.setLatLngs(FS.track.map(p=>[p.lat,p.lon]));if(FS.pos){const ll=[FS.pos.lat,FS.pos.lon];if(!FS.me){FS.acc=L.circle(ll,{radius:FS.pos.acc||20,color:'#0a5cff',weight:1,fillOpacity:.08}).addTo(FS.map);FS.me=L.circleMarker(ll,{radius:8,color:'#fff',weight:3,fillColor:'#0a5cff',fillOpacity:1}).addTo(FS.map)}else{FS.me.setLatLng(ll);FS.acc.setLatLng(ll).setRadius(FS.pos.acc||20)}}}

/* ---------- Posición ---------- */
function onRoute(p){const r=S.route;if(!r?.points?.length)return null;const q=Expedition.locate(r.points,p);if(!q)return null;const pace=Number($('#pace')?.value)||8,climb=r.summary.elevationComplete?Number($('#climb')?.value)||0:0,live=FC.trackStats(FS.track).pace;const usePace=live&&FS.track.length>20?Math.max(2,Math.min(60,live)):pace;const remKm=Math.max(0,r.summary.km-q.km),remUp=r.summary.elevationComplete?Math.max(0,r.summary.up-q.up):0,remMin=remKm*usePace+remUp/100*climb;return{...q,offM:q.distance*1000,remKm,remUp,eta:Date.now()+remMin*60000,usePace,live:!!(live&&FS.track.length>20)}}
function onPosition(raw){const c=raw.coords,p={lat:c.latitude,lon:c.longitude,ele:Number.isFinite(c.altitude)?c.altitude:null,acc:c.accuracy,t:raw.timestamp||Date.now(),speed:c.speed,heading:c.heading};FS.pos=p;
 if(!Number.isFinite(FS.heading)&&Number.isFinite(p.heading)&&p.speed>.6){FS.gpsHeading=p.heading}
 if($('#fieldRecord').checked&&FS.watch!==null&&p.acc<=50){const last=FS.track.at(-1);if(!last||FC.distance(last,p)*1000>=8||p.t-last.t>=60000){FS.track.push({lat:p.lat,lon:p.lon,ele:p.ele,t:p.t});if(FS.track.length>20000)FS.track.splice(0,FS.track.length-20000);if(Date.now()-FS.lastSave>15000){FS.lastSave=Date.now();lsSet('tm.track.v1',{startedAt:FS.startedAt,points:FS.track})}}}
 const q=onRoute(p);FS.q=q;
 if(q){const th=Number($('#offThreshold').value)||120;if(q.offM>th&&p.acc<Math.max(60,th/2)){FS.off.count++;if(FS.off.count>=2&&!FS.off.alerted){FS.off.alerted=true;fieldAlert('off',`Fuera del track: ${fmt(q.offM)} m. Comprueba el camino en el mapa.`,'danger',true)}}else if(q.offM<=th*.7){if(FS.off.alerted){fieldAlert('off','De nuevo sobre el track ✓','ok');setTimeout(()=>dismissAlert('off'),6000)}FS.off={count:0,alerted:false}}
  if(S.route?.data&&q.offM<100&&q.km>=.1&&Date.now()-FS.lastProgress>300000&&typeof progressAt==='function'){FS.lastProgress=Date.now();try{progressAt(q.km,p.acc)}catch{}}}
 if(navigator.onLine!==false&&FS.watch!==null&&Date.now()-FS.lastWeather>1200000)checkWeather();
 renderField()}
function setState(on,text){const s=$('#fieldState');s.classList.toggle('on',on);s.querySelector('span').textContent=text}
async function startTracking(){if(!navigator.geolocation){fieldAlert('gps','Este navegador no ofrece GPS.','warn');return}if(FS.watch!==null)return;if(!FS.startedAt||!FS.track.length)FS.startedAt=Date.now();lsSet('tm.track.v1',{startedAt:FS.startedAt,points:FS.track});setState(true,'Buscando satélites…');$('#fieldStart').hidden=true;$('#fieldStop').hidden=false;FS.turnAlarm={warned:false,fired:false};
 FS.watch=navigator.geolocation.watchPosition(pos=>{setState(true,`GPS ±${fmt(pos.coords.accuracy)} m`);onPosition(pos)},err=>{setState(false,err.code===1?'Permiso de ubicación denegado':'Sin señal GPS');if(err.code===1){fieldAlert('gps','Permite la ubicación en Ajustes → Safari → Ubicación (o en el navegador) para usar el seguimiento.','warn');stopTracking()}},{enableHighAccuracy:true,maximumAge:5000,timeout:30000});
 if($('#fieldWake').checked)requestWake();try{if('Notification'in globalThis&&Notification.permission==='default')Notification.requestPermission().catch(()=>{})}catch{}FS.ticker=setInterval(renderField,30000);if(typeof sfx==='function')sfx('ok')}
function stopTracking(){if(FS.watch!==null)navigator.geolocation?.clearWatch(FS.watch);FS.watch=null;clearInterval(FS.ticker);releaseWake();lsSet('tm.track.v1',{startedAt:FS.startedAt,points:FS.track});setState(false,FS.track.length?'Seguimiento en pausa':'GPS apagado');$('#fieldStart').hidden=false;$('#fieldStart').textContent=FS.track.length?'▶ Reanudar seguimiento':'▶ Iniciar seguimiento';$('#fieldStop').hidden=true;renderField()}
async function requestWake(){try{if(navigator.wakeLock&&!FS.wake){FS.wake=await navigator.wakeLock.request('screen');FS.wake.addEventListener?.('release',()=>{FS.wake=null})}}catch{}}
function releaseWake(){try{FS.wake?.release()}catch{}FS.wake=null}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&FS.watch!==null&&$('#fieldWake').checked)requestWake()});
$('#fieldWake').onchange=e=>{if(e.target.checked&&FS.watch!==null)requestWake();else releaseWake()};

/* ---------- Avisos ---------- */
function fieldAlert(id,text,kind='danger',loud=false){let el=$('#fa-'+id);if(!el){el=document.createElement('div');el.id='fa-'+id;$('#fieldAlerts').prepend(el)}el.className='field-alert '+kind;el.innerHTML=`<span>${esc(text)}</span><button type="button" class="quiet">OK</button>`;el.querySelector('button').onclick=()=>el.remove();if(kind!=='ok'){if(typeof sfx==='function')sfx('warn');try{navigator.vibrate?.(loud?[300,120,300,120,300]:[180])}catch{}if(loud||kind==='danger')notify(text)}else if(typeof sfx==='function')sfx('ok')}
function dismissAlert(id){$('#fa-'+id)?.remove()}
function notify(text){try{if(document.hidden&&'Notification'in globalThis&&Notification.permission==='granted')navigator.serviceWorker?.ready.then(r=>r.showNotification('TrailMeteo',{body:text,tag:'trailmeteo-field',renotify:true})).catch(()=>{})}catch{}}

/* ---------- Sol, luna y retorno ---------- */
function here(){return FS.pos||(S.route?.points?.[0])||S.location}
function sunNow(){const h=here(),now=Date.now();let t=FC.sunTimes(now,h.lat,h.lon);if(Number.isFinite(t.dusk)&&now>t.dusk+3600000){const n=FC.sunTimes(now+86400000,h.lat,h.lon);t={...n,tomorrow:true}}return t}
function turnInfo(){const t=sunNow(),margin=Number($('#turnMargin').value)||0,deadline=Number.isFinite(t.sunset)?t.sunset-margin*60000:null,now=Date.now();const start=FS.startedAt&&FS.track.length?FS.startedAt:(S.route?.start&&Math.abs(S.route.start-now)<16*3600000?S.route.start:now);if(!deadline||t.tomorrow)return{t,deadline,mode:'none'};if($('#turnMode').value==='outback'){const r=FC.turnaround({start,now,deadline});return{t,deadline,mode:'outback',...r}}const q=FS.q;return{t,deadline,mode:'through',eta:q?.eta??(S.route?.rows?currentPlan?.()?.arrival:null)}}
function renderSun(){const {t,deadline,mode,turn,remaining,late,eta}=turnInfo(),now=Date.now(),moon=FC.moonIllumination(now);
 if(mode==='outback'){$('#turnTime').textContent=fTime(turn);$('#turnTime').className='turn '+(late?'high':remaining<1800000?'medium':'');$('#turnText').textContent=late?`Ya has pasado tu hora de retorno (${fDur(-remaining)}). Vuelve ahora para llegar con luz.`:`Date la vuelta antes de esta hora para volver con ${$('#turnMargin').value} min de margen antes del ocaso. Quedan ${fDur(remaining)}.`;
  if(FS.watch!==null){if(!late&&remaining<600000&&!FS.turnAlarm.warned){FS.turnAlarm.warned=true;fieldAlert('turn','Quedan 10 minutos para tu hora de retorno.','warn',true)}if(late&&!FS.turnAlarm.fired){FS.turnAlarm.fired=true;fieldAlert('turn','Hora de dar la vuelta.','danger',true)}}}
 else if(mode==='through'){const ok=Number.isFinite(eta);$('#turnTime').textContent=fTime(deadline);const slack=ok?deadline-eta:null;$('#turnTime').className='turn '+(ok&&slack<0?'high':ok&&slack<1800000?'medium':'');$('#turnText').textContent=ok?(slack>=0?`Hora límite de llegada. Con tu ritmo llegas ≈ ${fTime(eta)}: ${fDur(slack)} de margen.`:`Llegarías ≈ ${fTime(eta)}, ${fDur(-slack)} después de la hora límite. Acorta la ruta o busca una salida antes.`):'Hora límite de llegada (ocaso menos margen). Carga una ruta y activa el GPS para comparar con tu llegada.'}
 else{$('#turnTime').textContent=t.tomorrow?'Mañana':'—';$('#turnText').textContent=t.tomorrow?`Ya es de noche. Amanece a las ${fTime(t.sunrise)}.`:'Sin datos de ocaso para esta posición.'}
 const rows=[['Amanecer',fTime(t.sunrise)],['Ocaso',fTime(t.sunset)],['Fin de la luz civil',fTime(t.dusk)],['Luz restante',Number.isFinite(t.sunset)&&!t.tomorrow?fDur(t.sunset-now):'—'],['Hora dorada',fTime(t.golden)],['Luna',`${moonGlyph(moon.phase)} ${Math.round(moon.fraction*100)} %`]];$('#sunRows').innerHTML=rows.map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('');
 if([t.dawn,t.dusk,t.sunrise,t.sunset].every(Number.isFinite)){const a=t.dawn-1800000,b=t.dusk+1800000,X=v=>Math.max(0,Math.min(100,(v-a)/(b-a)*100));$('#sunLine').innerHTML=`<svg viewBox="0 0 100 30" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="dayg" x1="0" x2="1"><stop offset="0" stop-color="#0a1621" stop-opacity=".15"/><stop offset=".5" stop-color="#ffb000" stop-opacity=".45"/><stop offset="1" stop-color="#0a1621" stop-opacity=".15"/></linearGradient></defs><rect x="${X(t.sunrise)}" y="12" width="${X(t.sunset)-X(t.sunrise)}" height="6" rx="3" fill="url(#dayg)"/><line x1="0" x2="100" y1="15" y2="15" stroke="currentColor" stroke-opacity=".2" stroke-width=".3"/>${Number.isFinite(deadline)?`<line x1="${X(deadline)}" x2="${X(deadline)}" y1="6" y2="24" stroke="#e0313b" stroke-width=".5"/>`:''}${now>a&&now<b?`<circle cx="${X(now)}" cy="15" r="2.2" fill="#0a5cff"/>`:''}</svg>`}else $('#sunLine').innerHTML=''}
function moonGlyph(p){return['🌑','🌒','🌓','🌔','🌕','🌖','🌗','🌘'][Math.round(p*8)%8]}

/* ---------- Lecturas principales ---------- */
function renderReadouts(){const p=FS.pos,q=FS.q,st=FC.trackStats(FS.track),t=sunNow(),th=Number($('#offThreshold').value)||120;const cell=(label,value,small='',cls='')=>`<div class="readout ${cls}"><span>${label}</span><strong>${value}</strong><small>${small}</small></div>`;
 const light=Number.isFinite(t.sunset)&&!t.tomorrow?t.sunset-Date.now():null;
 $('#fieldReadouts').innerHTML=[cell('Altitud GPS',p&&Number.isFinite(p.ele)?fmt(p.ele)+' m':'—',p?`±${fmt(p.acc)} m horiz.`:'Sin posición'),cell('Recorrido',q?fmt(q.km,1)+' km':st.km?fmt(st.km,1)+' km':'—',q?`quedan ${fmt(q.remKm,1)} km · +${fmt(q.remUp)} m`:'de tu track'),cell('Llegada estimada',q?fTime(q.eta):'—',q?(q.live?`ritmo real ${fmt(q.usePace,1)} min/km`:`ritmo plan ${fmt(q.usePace,1)} min/km`):'carga una ruta','' ),cell('Luz restante',light!==null?fDur(light):'—',`ocaso ${fTime(t.sunset)}`,light!==null&&light<3600000?'warn':''),cell('Fuera de ruta',q?fmt(q.offM)+' m':'—',`aviso a ${th} m`,q&&q.offM>th?'danger':q?'ok':''),cell('Desnivel +',st.up?'+'+fmt(st.up)+' m':'—',st.down?`−${fmt(st.down)} m`:'track propio'),cell('En marcha',st.moving?fDur(st.moving*1000):'—',st.elapsed?`total ${fDur(st.elapsed*1000)}`:''),cell('Ritmo',st.pace?fmt(st.pace,1)+'′/km':'—',p&&Number.isFinite(p.speed)?`${fmt(p.speed*3.6,1)} km/h ahora`:'medio en movimiento')].join('')}
function renderTrack(){const st=FC.trackStats(FS.track);$('#trackStats').innerHTML=[['Distancia',fmt(st.km,2)+' km'],['Desnivel',`+${fmt(st.up)} / −${fmt(st.down)} m`],['Puntos',fmt(FS.track.length)],['Inicio',FS.startedAt?fTime(FS.startedAt):'—'],['En marcha',fDur(st.moving*1000)],['Ritmo medio',st.pace?fmt(st.pace,1)+' min/km':'—']].map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('')}
function renderField(){if(!$('#fieldReadouts'))return;renderReadouts();renderSun();renderTrack();renderCompassTargets(false);renderCompass();renderSOS();drawCrumb()}

/* ---------- Brújula ---------- */
$('#compass').innerHTML=`<svg viewBox="-110 -110 220 220" aria-hidden="true"><circle r="100" fill="none" stroke="currentColor" stroke-opacity=".15"/><circle r="72" fill="none" stroke="currentColor" stroke-opacity=".08"/><g class="rose">${Array.from({length:72},(_,i)=>{const a=i*5,l=i%18===0?14:i%6===0?9:4;return `<line x1="0" y1="${-100}" x2="0" y2="${-100+l}" stroke="currentColor" stroke-opacity="${i%6===0?.6:.25}" stroke-width="${i%18===0?2:1}" transform="rotate(${a})"/>`}).join('')}<text class="north" x="0" y="-74" text-anchor="middle">N</text><text x="78" y="5" text-anchor="middle">E</text><text x="0" y="86" text-anchor="middle">S</text><text x="-78" y="5" text-anchor="middle">O</text></g><g class="target"><path d="M0 -92 L9 -64 L0 -70 L-9 -64Z" fill="#ff4d1f"/></g><path d="M0 -44 L7 0 L0 -6 L-7 0Z" fill="currentColor"/><circle r="4" fill="currentColor"/></svg>`;
function targets(){const out=[];const r=S.route;if(FS.track[0])out.push({id:'trackstart',name:'Inicio de mi track',lat:FS.track[0].lat,lon:FS.track[0].lon});if(r?.points?.length){out.push({id:'rstart',name:'Inicio de la ruta',...r.points[0]});out.push({id:'rend',name:'Final de la ruta',...r.points.at(-1)})}for(const p of lsGet('tm.points',[]))out.push({id:'pt'+p.t,name:'📍 '+p.name,lat:p.lat,lon:p.lon,saved:p.t});return out}
function renderCompassTargets(force=true){const sel=$('#compassTarget'),list=targets(),key=list.map(t=>t.id).join();if(!force&&sel.dataset.key===key)return;const prev=sel.value;sel.dataset.key=key;sel.innerHTML=list.length?list.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join(''):'<option value="">Sin destinos: guarda un punto o carga una ruta</option>';if(list.some(t=>t.id===prev))sel.value=prev}
function renderCompass(){const h=Number.isFinite(FS.heading)?FS.heading:Number.isFinite(FS.gpsHeading)?FS.gpsHeading:null;const rose=$('#compass .rose'),tgt=$('#compass .target');if(Number.isFinite(h)){rose.style.transform=`rotate(${-h}deg)`;$('#compassHeading').textContent=`${Math.round(h)}° ${FC.cardinal(h)}`;$('#compassSrc').textContent=Number.isFinite(FS.heading)?'Brújula magnética del teléfono':'Rumbo GPS (solo al caminar)'}const t=targets().find(x=>x.id===$('#compassTarget').value);if(t&&FS.pos){const b=FC.bearing(FS.pos,t),d=FC.distance(FS.pos,t);tgt.style.display='';tgt.style.transform=`rotate(${b-(Number.isFinite(h)?h:0)}deg)`;$('#compassTargetInfo').innerHTML=`<b>${d<1?fmt(d*1000)+' m':fmt(d,2)+' km'}</b> en línea recta · rumbo ${Math.round(b)}° ${FC.cardinal(b)}${!Number.isFinite(h)?' (respecto al norte)':''}${t.saved?` · <button type="button" class="quiet" data-del-point="${t.saved}" style="min-height:32px;padding:2px 10px">quitar</button>`:''}`}else{tgt.style.display='none';$('#compassTargetInfo').textContent=FS.pos?'Elige un destino.':'Necesita tu posición GPS.'}}
function onOrient(e){let h=null;if(Number.isFinite(e.webkitCompassHeading))h=e.webkitCompassHeading;else if(e.absolute&&Number.isFinite(e.alpha))h=360-e.alpha;if(h===null)return;h=(h+(screen.orientation?.angle||0)+360)%360;FS.heading=FS.heading==null?h:FS.heading+((((h-FS.heading)%360)+540)%360-180)*.25;FS.heading=(FS.heading+360)%360;if(!FS.raf)FS.raf=requestAnimationFrame(()=>{FS.raf=0;renderCompass()})}
$('#compassEnable').onclick=async()=>{try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const r=await DeviceOrientationEvent.requestPermission();if(r!=='granted')throw Error('denegado')}window.addEventListener('deviceorientationabsolute',onOrient,true);window.addEventListener('deviceorientation',onOrient,true);$('#compassSrc').textContent='Leyendo sensor… mueve el teléfono en forma de 8';$('#compassEnable').textContent='🧭 Brújula activa'}catch{$('#compassSrc').textContent='Sin acceso a la brújula. Se usará el rumbo GPS al caminar.'}};
$('#compassTarget').onchange=renderCompass;
$('#compassTargetInfo').addEventListener('click',e=>{const b=e.target.closest('[data-del-point]');if(!b)return;lsSet('tm.points',lsGet('tm.points',[]).filter(p=>String(p.t)!==b.dataset.delPoint));renderCompassTargets();renderCompass()});
$('#pointSave').onclick=()=>{const save=p=>{const name=$('#pointName').value.trim()||'Punto '+fTime(Date.now());const list=lsGet('tm.points',[]);list.unshift({name,lat:p.lat,lon:p.lon,t:Date.now()});lsSet('tm.points',list.slice(0,30));$('#pointName').value='';renderCompassTargets();$('#compassTarget').value='pt'+list[0].t;renderCompass();if(typeof sfx==='function')sfx('ok')};if(FS.pos)save(FS.pos);else navigator.geolocation?.getCurrentPosition(pos=>{onPosition(pos);save(FS.pos)},()=>fieldAlert('gps','No se pudo obtener la posición para guardar el punto.','warn'),{enableHighAccuracy:true,timeout:20000})};

/* ---------- Tormenta ---------- */
$('#flashBtn').onclick=()=>{FS.flashAt=performance.now();$('#thunderBtn').disabled=false;$('#thunderBtn').classList.add('primary');clearInterval(FS.flashTimer);FS.flashTimer=setInterval(()=>{const s=(performance.now()-FS.flashAt)/1000;$('#stormOut').innerHTML=`<strong>${fmt(s,1)} s</strong><p class="muted">≈ ${fmt(FC.stormDistance(s),1)} km… pulsa al oír el trueno.</p>`;if(s>90){clearInterval(FS.flashTimer);$('#thunderBtn').disabled=true}},100)};
$('#thunderBtn').onclick=()=>{if(FS.flashAt==null)return;clearInterval(FS.flashTimer);const s=(performance.now()-FS.flashAt)/1000;FS.flashAt=null;$('#thunderBtn').disabled=true;$('#thunderBtn').classList.remove('primary');recordStrike(s)};
function recordStrike(seconds,at=Date.now()){const km=FC.stormDistance(seconds);FS.strikes.push({t:at,km});FS.strikes=FS.strikes.slice(-8);const prev=FS.strikes.at(-2),trend=prev?(km<prev.km-.3?'se acerca':km>prev.km+.3?'se aleja':'estable'):'';const close=km<10;$('#stormOut').innerHTML=`<strong class="${close?'high':km<16?'medium':''}">${fmt(km,1)} km</strong><p>${fmt(seconds,1)} s entre relámpago y trueno${trend?` · la tormenta <b>${trend}</b>`:''}.</p><p class="${close?'high':'muted'}">${close?'Estás dentro del radio de caída de rayos. Baja de crestas y cumbres, aléjate de árboles aislados, agua y metal; no te refugies en la boca de cuevas pequeñas. Si no hay refugio: agáchate sobre la mochila, pies juntos. Espera 30 min desde el último trueno.':'Vigila la evolución: si baja de 30 s (10 km), busca refugio.'}</p><p class="footnote">${FS.strikes.map(s=>`${fTime(s.t)} · ${fmt(s.km,1)} km`).join(' → ')}</p>`;if(close)fieldAlert('storm',`Rayos a ${fmt(km,1)} km: busca refugio y evita zonas expuestas.`,'danger',true);return{km,trend}}

/* ---------- Track ---------- */
$('#trackGpx').onclick=()=>{if(FS.track.length<2){$('#trackNote').textContent='Aún no hay puntos suficientes.';return}const name='Mi track '+new Date(FS.startedAt||Date.now()).toLocaleDateString('es-ES');(typeof downloadFile==='function'?downloadFile:(n,t)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t]));a.download=n;a.click()})(name.replace(/[^\w-]+/g,'_')+'.gpx',FC.toGPX(name,FS.track),'application/gpx+xml')};
$('#trackUse').onclick=async()=>{if(FS.track.length<2){$('#trackNote').textContent='Aún no hay puntos suficientes.';return}await importRoute(new File([FC.toGPX('Mi track',FS.track)],'mi-track.gpx',{type:'application/gpx+xml'}));showTab('route')};
$('#trackClear').onclick=e=>{if(e.target.dataset.confirm!=='1'){e.target.dataset.confirm='1';e.target.textContent='¿Seguro? Pulsa otra vez';setTimeout(()=>{e.target.dataset.confirm='';e.target.textContent='Borrar'},4000);return}FS.track=[];FS.startedAt=FS.watch!==null?Date.now():null;lsSet('tm.track.v1',{startedAt:FS.startedAt,points:[]});e.target.dataset.confirm='';e.target.textContent='Borrar';renderField()};
(function restoreTrack(){const saved=lsGet('tm.track.v1',null);if(saved?.points?.length&&Date.now()-(saved.points.at(-1).t||0)<36*3600000){FS.track=saved.points;FS.startedAt=saved.startedAt;$('#fieldStart').textContent='▶ Reanudar seguimiento';$('#trackNote').textContent=`Track recuperado: ${fmt(saved.points.length)} puntos desde las ${fTime(saved.startedAt)}.`}})();

/* ---------- Vigilancia meteorológica ---------- */
async function checkWeather(){const p=FS.pos||here();if(!p||!$('#watchOut'))return;FS.lastWeather=Date.now();$('#watchOut').innerHTML='<span class="spinner"></span>Consultando la previsión en tu posición…';try{const d=await json(forecastURL(p.lat.toFixed(3),p.lon.toFixed(3),{forecast_days:'2',current:''}),600000);const now=Date.now(),hs=hours(d).filter(h=>h.time>=now-1800000&&h.time<=now+3*3600000);if(!hs.length)throw Error('sin horas');if(!$('#watchOut'))return;const bad=hs.map(h=>({h,a:assess(h)})).filter(x=>x.a.level==='high');$('#watchOut').innerHTML=`<div class="tablewrap"><table><tbody>${hs.map(h=>{const a=assess(h);return `<tr><td>${fTime(h.time)}</td><td>${weather(h.weather_code)[0]} ${fmt(h.temperature_2m)}°</td><td>${fmt(h.precipitation,1)} mm</td><td>${fmt(h.wind_gusts_10m)} km/h</td><td class="${a.level}">${esc(a.risks.join(' · ')||a.label)}</td></tr>`}).join('')}</tbody></table></div><p class="footnote">Consultado ${fTime(now)} para ${p.lat.toFixed(3)}, ${p.lon.toFixed(3)}${FS.watch!==null?' · próxima comprobación en 20 min':''}.</p>`;if(bad.length)fieldAlert('wx',`Previsión en tu zona a las ${fTime(bad[0].h.time)}: ${bad[0].a.risks.join(', ')}.`,'danger',true);else dismissAlert('wx')}catch(e){if(!$('#watchOut'))return;$('#watchOut').textContent='No se pudo consultar (sin cobertura o servicio no disponible). Se reintentará.';FS.lastWeather=Date.now()-900000}}
$('#watchNow').onclick=checkWeather;

/* ---------- SOS ---------- */
function sosMessage(){const p=FS.pos;if(!p)return null;const u=FC.toUTM(p.lat,p.lon),m=lsGet('tm.medical',{});return `SOS montaña${m.name?' · '+m.name:''}. Posición: ${p.lat.toFixed(5)}, ${p.lon.toFixed(5)} (UTM ${u.text}). ${Number.isFinite(p.ele)?'Altitud ≈ '+Math.round(p.ele)+' m. ':''}Precisión ±${Math.round(p.acc)} m. Hora ${fTime(p.t)}.${S.route?.name?' Ruta: '+S.route.name+'.':''}${m.blood?' Grupo '+m.blood+'.':''}${m.allergies?' Alergias: '+m.allergies+'.':''}${m.meds?' Medicación: '+m.meds+'.':''} https://www.openstreetmap.org/?mlat=${p.lat.toFixed(5)}&mlon=${p.lon.toFixed(5)}#map=16/${p.lat.toFixed(5)}/${p.lon.toFixed(5)}`}
function renderSOS(){const p=FS.pos;if(p){const u=FC.toUTM(p.lat,p.lon);$('#sosCoords').innerHTML=`<div class="coords"><small>Grados decimales</small>${p.lat.toFixed(5)}, ${p.lon.toFixed(5)}</div><div class="coords"><small>UTM (ETRS89/WGS84)</small>${u.text}</div><div class="coords"><small>Grados, minutos, segundos</small>${FC.toDMS(p.lat,p.lon)}</div><p class="muted">${Number.isFinite(p.ele)?`Altitud ≈ ${fmt(p.ele)} m · `:''}precisión ±${fmt(p.acc)} m · ${fTime(p.t)}</p>`}const phone=(lsGet('tm.medical',{}).phone||'').replace(/[^\d+]/g,''),msg=sosMessage();$('#sosSms').href=`sms:${phone}${/iP(hone|ad|od)/.test(navigator.userAgent)?'&':'?'}body=${encodeURIComponent(msg||'SOS montaña. Necesito ayuda.')}`;$('#sosSms').textContent=phone?'✉ SMS a mi contacto':'✉ SMS (añade contacto abajo)'}
function locateOnce(){$('#sosLocate').textContent='📍 Buscando…';navigator.geolocation?.getCurrentPosition(pos=>{onPosition(pos);$('#sosLocate').textContent='📍 Actualizar posición'},()=>{$('#sosLocate').textContent='📍 Reintentar posición';fieldAlert('gps','No se pudo obtener la posición. Sal a un lugar despejado y reintenta.','warn')},{enableHighAccuracy:true,timeout:25000,maximumAge:10000})}
$('#sosLocate').onclick=locateOnce;
$('#sosCopy').onclick=async()=>{const m=sosMessage();if(!m){locateOnce();return}try{await navigator.clipboard.writeText(m);$('#sosCopy').textContent='✓ Copiado'}catch{$('#sosCopy').textContent='No se pudo copiar'}setTimeout(()=>$('#sosCopy').textContent='⧉ Copiar mensaje',3000)};
$('#sosShare').onclick=async()=>{const m=sosMessage();if(!m){locateOnce();return}try{if(navigator.share)await navigator.share({title:'SOS · mi posición',text:m});else{await navigator.clipboard.writeText(m);$('#sosShare').textContent='✓ Copiado'}}catch{}};
const MORSE_SOS=[1,1,1,0,3,3,3,0,1,1,1,0,0,0];
$('#sosWhistle').onclick=()=>{if(FS.whistle){clearInterval(FS.whistle);FS.whistle=null;$('#sosWhistle').textContent='📣 Silbato SOS';return}const AC=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AC)return;const ctx=FX?.ctx||new AC();if(FX)FX.ctx=ctx;ctx.resume?.();let i=0;const beep=len=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='square';o.frequency.value=3100;g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.5,ctx.currentTime+.01);g.gain.setValueAtTime(.5,ctx.currentTime+len);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+len+.02);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+len+.05)};FS.whistle=setInterval(()=>{const u=MORSE_SOS[i++%MORSE_SOS.length];if(u)beep(u===1?.18:.55)},700);$('#sosWhistle').textContent='■ Parar silbato'};
$('#sosStrobe').onclick=()=>{document.body.insertAdjacentHTML('beforeend','<div class="strobe" id="strobe" role="button" tabindex="0" aria-label="Detener luz SOS">Luz SOS en marcha<br><small>Toca para salir</small></div>');const el=$('#strobe');let i=0,step=0;const seq=[1,1,1,3,3,3,1,1,1];const run=()=>{if(!$('#strobe'))return;const u=seq[i%seq.length];el.classList.add('on');FS.strobe=setTimeout(()=>{el.classList.remove('on');i++;FS.strobe=setTimeout(run,i%seq.length===0?1400:220)},u===1?220:700)};run();requestWake();el.onclick=()=>{clearTimeout(FS.strobe);el.remove()}};
$('#sosButton')?.addEventListener('click',()=>{showTab('field');setTimeout(()=>{$('#sosPanel').scrollIntoView({behavior:'smooth',block:'start'});if(!FS.pos)locateOnce()},120)});

/* ---------- Integración ---------- */
$('#fieldStart').onclick=startTracking;$('#fieldStop').onclick=stopTracking;
['turnMode','turnMargin','offThreshold'].forEach(id=>$('#'+id).addEventListener('change',()=>{FS.turnAlarm={warned:false,fired:false};renderField()}));
try{const tm=lsGet('tm.turn',null);if(tm){$('#turnMode').value=tm.mode;$('#turnMargin').value=tm.margin}}catch{}
['turnMode','turnMargin'].forEach(id=>$('#'+id).addEventListener('change',()=>lsSet('tm.turn',{mode:$('#turnMode').value,margin:$('#turnMargin').value})));
const fieldShowTab=showTab;showTab=function(tab){fieldShowTab(tab);if(tab==='field'){setTimeout(()=>{ensureFieldMap();FS.map?.invalidateSize();drawFieldRoute()},60);renderField()}};
const fieldImport=importRoute;importRoute=async function(file){await fieldImport(file);FS.q=null;FS.off={count:0,alerted:false};drawFieldRoute();renderField()};
renderField();
globalThis.Field={state:FS,onPosition,renderField,recordStrike,sosMessage,turnInfo,checkWeather,start:startTracking,stop:stopTracking};
