'use strict';
/* Mastines reportados: avisos con fecha y comportamiento. Comunitario con Firestore (si hay Firebase) o solo en este dispositivo. */
const DOG={map:null,layer:null,reports:[],days:60,pick:null,pickMarker:null,remote:false,db:null};
const DOG_BEH={calm:['Tranquilos','#1d9b72'],bark:['Avisan ladrando','#d4861a'],approach:['Se acercan','#ff6a33'],aggr:['Agresivos','#e14545']};
$('#terrainApp')?.insertAdjacentHTML('beforeend',`<section class="card" id="dogCard"><div class="viz-title"><div><p class="eyebrow">Mastines reportados</p><h2>Dónde y cuándo</h2></div><div class="cn-filters" style="padding:0" role="toolbar">${[[7,'7 días'],[30,'30 días'],[60,'60 días'],[365,'1 año']].map(([d,l])=>`<button type="button" data-dog-days="${d}" aria-pressed="${d===60}">${l}</button>`).join('')}</div></div><div id="dogAlert"></div><div class="cn-atlas" style="height:clamp(320px,50vh,520px)"><div class="map" id="dogMap" aria-label="Mapa de avisos de mastines"></div></div><div class="dog-legend">${Object.values(DOG_BEH).map(([l,c])=>`<span><i style="display:inline-block;width:9px;height:9px;border-radius:50%;background:${c};margin-right:6px"></i>${l}</span>`).join('')}<span id="dogSource"></span></div><div id="dogList"></div>
<details><summary>Reportar mastines · toca el mapa para situarlos</summary><form class="dog-form" id="dogForm"><label>Fecha<input type="date" name="date" required></label><label>Número de perros<input type="number" name="count" min="1" max="30" value="2" required></label><label>Comportamiento<select name="beh">${Object.entries(DOG_BEH).map(([k,[l]])=>`<option value="${k}">${l}</option>`).join('')}</select></label><label>Con rebaño<select name="flock"><option value="yes">Sí</option><option value="no">No</option><option value="unk">No lo sé</option></select></label><label class="wide">Lugar y notas (sin datos personales)<input name="notes" maxlength="200" placeholder="Majada, collado, junto al camino…"></label><p class="wide muted" id="dogPos">Toca el mapa para marcar dónde estaban.</p><button class="primary wide" type="submit">Guardar aviso</button></form></details>
<details><summary>Cómo actuar ante mastines</summary><p>Los mastines protegen el ganado: su trabajo es alejarte del rebaño, no perseguirte. Rodea el rebaño a distancia y no te interpongas entre perros y animales. No corras, no grites ni les apuntes con el bastón; camina tranquilo, de lado y sin mirarles fijamente. En bici, bájate y camina. Si se acercan ladrando, detente, háblales en tono calmado y deja que te huelan antes de seguir despacio. Si hay pastor, avísale.</p></details><p class="footnote">Avisos aportados por usuarios, sin verificación. Un aviso antiguo no significa que el rebaño siga allí: los rebaños se mueven con los pastos.</p></section>`);
function dogCfg(){try{return typeof firebaseConfig==='function'?firebaseConfig():null}catch{return null}}
async function dogDB(){if(DOG.db)return DOG.db;const cfg=dogCfg();if(!cfg)return null;const v=typeof FIREBASE_SDK!=='undefined'?FIREBASE_SDK:'12.0.0';const [{initializeApp,getApps},fs]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${v}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${v}/firebase-firestore.js`)]);const app=getApps().find(a=>a.name==='trailmeteo')||initializeApp(cfg,'trailmeteo');DOG.db={db:fs.getFirestore(app),fs};return DOG.db}
function localReports(){try{return JSON.parse(localStorage.getItem('tm.dogs'))||[]}catch{return[]}}
function validReport(r){return !!(r&&finite(r.lat)&&finite(r.lon)&&Math.abs(r.lat)<=90&&Math.abs(r.lon)<=180&&finite(r.t)&&DOG_BEH[r.beh]&&finite(r.count))}
async function loadDogs(){let remote=[];DOG.remote=false;try{const d=await dogDB();if(d){const {fs,db}=d,since=Date.now()-366*86400000;const snap=await fs.getDocs(fs.query(fs.collection(db,'mastines'),fs.where('t','>=',since),fs.orderBy('t','desc'),fs.limit(800)));remote=snap.docs.map(x=>({id:x.id,...x.data(),remote:true}));DOG.remote=true}}catch(e){$('#dogSource').textContent='· Firebase no disponible ('+(e.code||e.message)+'): solo avisos de este dispositivo'}DOG.reports=[...remote,...localReports().filter(l=>!remote.some(r=>r.t===l.t&&Math.abs(r.lat-l.lat)<1e-5))].filter(validReport);if(DOG.remote)$('#dogSource').textContent=`· ${remote.length} avisos de la comunidad`;else if(!dogCfg())$('#dogSource').textContent='· Solo en este dispositivo (configura Firebase en el copiloto para compartirlos)';renderDogs()}
function nearRoute(days=60,maxKm=.5){const r=S.route;if(!r?.points?.length)return[];const since=Date.now()-days*86400000;return DOG.reports.filter(d=>d.t>=since).map(d=>({...d,q:Expedition.locate(r.points,d)})).filter(d=>d.q&&d.q.distance<=maxKm).sort((a,b)=>a.q.km-b.q.km)}
function ensureDogMap(){if(DOG.map||!window.L||$('#dogMap')?.offsetParent===null)return;const c=S.route?.points?.[0]||S.location;DOG.map=L.map('dogMap',{maxZoom:17}).setView([c.lat,c.lon],12);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(DOG.map);DOG.map.on('click',e=>{DOG.pick={lat:e.latlng.lat,lon:e.latlng.lng};DOG.pickMarker?.remove();DOG.pickMarker=L.circleMarker(e.latlng,{radius:10,color:'#10161a',weight:2,dashArray:'3 3',fillOpacity:0}).addTo(DOG.map);$('#dogPos').textContent=`Posición: ${DOG.pick.lat.toFixed(5)}, ${DOG.pick.lon.toFixed(5)}`;$('#dogForm').closest('details').open=true});renderDogs()}
function renderDogs(){const since=Date.now()-DOG.days*86400000,list=DOG.reports.filter(d=>d.t>=since).sort((a,b)=>b.t-a.t);if(DOG.map){DOG.layer?.remove();const items=list.map(d=>{const age=(Date.now()-d.t)/86400000,op=Math.max(.35,1-age/DOG.days);return L.circleMarker([d.lat,d.lon],{radius:6+Math.min(8,d.count),color:'#fff',weight:2,fillColor:DOG_BEH[d.beh][1],fillOpacity:op}).bindPopup(`<b>${d.count} mastín${d.count>1?'es':''} · ${DOG_BEH[d.beh][0]}</b><br>${new Date(d.t).toLocaleDateString('es-ES',{day:'numeric',month:'long',year:'numeric'})}${d.flock==='yes'?' · con rebaño':''}<br><small>${esc(d.notes||'')}</small>`)});if(S.route&&window.L){const g=new Map();for(const p of S.route.points){if(!g.has(p.segment))g.set(p.segment,[]);g.get(p.segment).push([p.lat,p.lon])}for(const line of g.values())items.push(L.polyline(line,{color:'#13a6b4',weight:4,opacity:.8}))}DOG.layer=L.featureGroup(items).addTo(DOG.map);if(items.length&&!DOG.fitted){DOG.fitted=true;try{DOG.map.fitBounds(DOG.layer.getBounds(),{padding:[30,30],maxZoom:14})}catch{}}}
 const near=nearRoute(DOG.days);$('#dogAlert').innerHTML=S.route?(near.length?`<p class="dog-alert"><b>${near.length} aviso${near.length>1?'s':''} a menos de 500 m de tu ruta</b> en los últimos ${DOG.days} días: ${near.slice(0,4).map(d=>`km ${fmt(d.q.km,1)} (${DOG_BEH[d.beh][0].toLowerCase()}, ${new Date(d.t).toLocaleDateString('es-ES',{day:'numeric',month:'short'})})`).join(' · ')}.</p>`:`<p class="muted">Sin avisos cerca de tu ruta en los últimos ${DOG.days} días.</p>`):'';
 $('#dogList').innerHTML=list.slice(0,8).map(d=>`<div class="dog-row"><div><b>${d.count} · ${DOG_BEH[d.beh][0]}</b>${d.flock==='yes'?' · con rebaño':''}<br><small>${new Date(d.t).toLocaleDateString('es-ES',{weekday:'short',day:'numeric',month:'short',year:'numeric'})} · ${d.lat.toFixed(3)}, ${d.lon.toFixed(3)}${d.notes?' · '+esc(d.notes):''}${d.remote?'':' · local'}</small></div></div>`).join('')||`<p class="muted">Sin avisos en los últimos ${DOG.days} días.</p>`}
$('#dogCard')?.addEventListener('click',e=>{const b=e.target.closest('[data-dog-days]');if(!b)return;DOG.days=Number(b.dataset.dogDays);$$('[data-dog-days]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderDogs()});
$('#dogForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.target;if(!DOG.pick){$('#dogPos').textContent='Primero toca el mapa para marcar la posición.';return}const date=new Date(f.date.value+'T12:00');if(!finite(date.getTime())||date>new Date()){$('#dogPos').textContent='Revisa la fecha.';return}const rep={lat:Math.round(DOG.pick.lat*1e5)/1e5,lon:Math.round(DOG.pick.lon*1e5)/1e5,t:date.getTime(),count:Math.max(1,Math.min(30,Number(f.count.value)||1)),beh:f.beh.value,flock:f.flock.value,notes:f.notes.value.trim().slice(0,200)};if(!validReport(rep))return;let shared=false;try{const d=await dogDB();if(d){await d.fs.addDoc(d.fs.collection(d.db,'mastines'),{...rep,created:d.fs.serverTimestamp()});shared=true}}catch{}if(!shared){const l=localReports();l.unshift(rep);try{localStorage.setItem('tm.dogs',JSON.stringify(l.slice(0,300)))}catch{}}$('#dogPos').textContent=shared?'Aviso compartido con la comunidad. Gracias.':'Aviso guardado en este dispositivo.';DOG.pick=null;DOG.pickMarker?.remove();f.notes.value='';if(typeof sfx==='function')sfx('ok');loadDogs()});
const today=new Date();$('#dogForm')&&($('#dogForm').date.value=localInput(today).slice(0,10));
const dogShowTab=showTab;showTab=function(tab){dogShowTab(tab);if(tab==='terrain'){setTimeout(()=>{ensureDogMap();DOG.map?.invalidateSize()},80);if(!DOG.loaded){DOG.loaded=true;loadDogs()}else renderDogs()}};
const dogImport=importRoute;importRoute=async function(f){await dogImport(f);DOG.fitted=false;renderDogs()};
globalThis.TMDogs={load:loadDogs,nearRoute,get reports(){return DOG.reports},get map(){return DOG.map},validReport};
